# Site settings
title: Max小站😉
SEOTitle: Max小站
header-img: img/post-bg-desk.jpg
email: 0xc00005@gmail.com
description: "Max的小小博客，不定期更新，但是干货什么的就是有生之年了....."
keyword: "0xC00005, Jingwei Zhang, Max - Jingwei Zhang, Max Zhang, Max, 2860520591, Atto Musk, Atto, 棱镜"
url: "http://0xC00005.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/0xC000005/0xC000005.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "
0xC00005，是🍁绝美黑长直！

前OIer，Python🦎gcd了，咸鱼数据科学给👴爪巴。不定时写文产粮。喜欢结交大佬了！
"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: true
#weibo_username:     c8137f32d573
#你要是敢社工的话那对不起，你妈死了！
zhihu_username:     wang-li-jun-76-22
github_username:    0xC000005
facebook_username:  0xC00005
jianshu_username:   c8137f32d573
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# 评论系统 Disqus（https://disqus.com/）
disqus_username: '0xC00005'

# Gitalk
#gitalk:
#  enable: true    #是否开启Gitalk评论
#  clientID: cca4e854a42a1b5a84d9  #生成的clientID
#  clientSecret: 04333bdeb4b282b73efa46d6f3922cbea61be1c0  #同上
#  repo: 0xC000005.github.io     #仓库名称
#  owner: '0xC000005'    #github用户名
#  admin: '0xC000005'
#  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68
#在北美连百度统计都要墙掉的嘛？QAQ

# Google Analytics
ga_track_id: 'UA-112677501-1'            # Format: UA-xxxxxx-xx
ga_domain: auto           # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "🍺逼乎Zhihu",
        href: "https://www.zhihu.com/people/wang-li-jun-76-22/activities"
    },{
        title: "👌简书Jianshu",
        href: "https://www.jianshu.com/u/c8137f32d573"
    },{
        title: "😘来QQ撩小姐姐?",
        href: "http://wpa.qq.com/msgrd?v=3&uin=2860520591&site=qq&menu=yes"
    },{
        title: "🎉小破站BiliBili",
        href: "https://space.bilibili.com/33057937#/"
    },{
        title: "🎈北美日常instagram",
        href: "https://www.instagram.com/m04.zhang/"
    }
]
